%% =====================================================================
%  SIFT Pipeline: Time-Varying Directed Connectivity Between Cortical Sources
%  ---------------------------------------------------------------------
%  Assumes:
%    - EEGLAB started, SIFT plugin installed
%    - EEG dataset already loaded with epoched data
%    - ICA/AMICA decomposition completed (EEG.icaweights, EEG.icasphere set)
%    - Source indices of interest known per subject
%  =====================================================================


% Add the necessary paths
addpath(genpath('D:\Morteza\MyProjects\ANSYMB2024\Code'))
EEGLAB_path = 'D:\Morteza\Toolboxes\EEGLAB\eeglab2026.0.0';
data_path = 'D:\Morteza\MyProjects\ANSYMB2024\data\';
processing_path = 'D:\Morteza\MyProjects\ANSYMB2024\Code\Matlab\data_processing\';
epoched_EEG_path = [data_path, '5_single-subject-EEG-analysis\', ...
    'timewarp_test\Epoched_data'];



% ---- USER PARAMETERS ----------------------------------------------------
freqRange       = 3:1:60;              % frequencies to estimate (Hz)
windowStepSec   = 0.02;                % step size (sec)
modelOrderRange = [1 30];              % search range for model order
finalModelOrder = [];                  % set later after inspecting criteria; leave empty for now
epochTimeRange  = [];                  % [] = use full epoch; or e.g. [-0.5 3.5]
verbosity       = 2;                   % 0=silent, 1=text, 2=text+graphics


% Load the EEG dataset
this_path = pwd; 
cd(EEGLAB_path)
if ~exist('ALLCOM','var')
	eeglab;
end
cd(this_path)
% Epoched EEG dataset (after non-experimental periods were removed)
cd(epoched_EEG_path)
thisSubjectID = 18;            
fileName = ['sub-', num2str(thisSubjectID), '_cleaned_with_ICA_epoched.set'];
EEG = pop_loadset('filename', fileName);
cd(this_path)


% ---- SANITY CHECK -------------------------------------------------------
if isempty(EEG.icaweights)
    error('No ICA decomposition found. Run AMICA/ICA first.');
end



%% =====================================================================
%  STEP 0: BUILD IC MAP AND SELECT THIS SUBJECT'S SOURCES
%  =====================================================================

% load the Subjects_ICs_in_clusters 
load("Subjects_ICs_in_clusters.mat") % will assign to SUBJECTS_ICS
subjectMap = build_subject_ic_map(SUBJECTS_ICS);

% to do on 07.05.2026
% note to be added: run again "extract_Subjects_ICs_in_cluster.m"
% the new Prime_Visual study has less in common with R/L parieto-occipital

entry = subjectMap([subjectMap.subjectID] == thisSubjectID);
if isempty(entry)
    error('Subject %d not found in SUBJECTS_ICS.', thisSubjectID);
end

srcIdx    = entry.icIdx;
srcLabels = entry.regionNames;

fprintf('\n=== Subject %d: using %d ICs ===\n', thisSubjectID, numel(srcIdx));
for i = 1:numel(srcIdx)
    fprintf('   IC%2d -> %s\n', srcIdx(i), srcLabels{i});
end

% --- Validate IC indices against this subject's EEG ---
if max(srcIdx) > size(EEG.icaweights, 1)
    error('IC index %d exceeds number of components (%d) in EEG.', ...
          max(srcIdx), size(EEG.icaweights, 1));
end

% --- Compute per-subject window length ---
M  = numel(srcIdx);
N  = EEG.trials;
Fs = EEG.srate;
pUpper = modelOrderRange(2);

W_rule    = ceil(1.2 * 10 * M^2 * pUpper / N);    % rule of thumb + 20% margin
W_freq    = ceil(1.0 * Fs / min(freqRange));      % >=1 cycle of lowest freq
W_samples = max(W_rule, W_freq);
windowLenSec = W_samples / Fs;

fprintf('\nWindow length: %d samples (%.3f s)  [rule=%d, freq-floor=%d]\n\n', ...
        W_samples, windowLenSec, W_rule, W_freq);

% Warn if window is large relative to epoch
if windowLenSec > 0.5 * (EEG.pnts / Fs)
    warning('Window (%.2fs) > half the epoch. Consider fewer ICs or more trials.', ...
            windowLenSec);
end






%% =====================================================================
%  STEP 1: PREPROCESSING
%  ---------------------------------------------------------------------
%  - Selects the components of interest
%  - Performs ensemble + temporal normalization (recommended for AMVAR
%    with multi-trial data; removes ERP, improves local stationarity)
%  =====================================================================

% --- Subset components: keep only the ICs of interest ---
EEG = pop_subcomp(EEG, srcIdx, 0, 1);   
% args: (EEG, components_to_keep, plotflag=0, keep_flag=1)
% keep_flag=1 means "keep these and discard the rest"

EEG = pop_pre_prepData(EEG, 'nogui', ...
    'VerbosityLevel',   verbosity, ...
    'SignalType',       {'Components'}, ...
    'VariableNames',    srcLabels, ...
    'Detrend',          {'verb', 0, 'method', {'linear'}}, ...
    'NormalizeData',    {'verb', 0, 'method', {'time','ensemble'}}, ...
    'BadDataSegments',  [], ...
    'TrialsToKeep',     [], ...
    'BalanceTrials',    false);

% Restrict to chosen components (alternative way if above doesn't filter)
EEG.CAT.curComps    = srcIdx;
EEG.CAT.curComponentNames = arrayfun(@(i) sprintf('IC%d',i), srcIdx, 'uni', 0);

%% =====================================================================
%  STEP 2: MODEL ORDER SELECTION
%  ---------------------------------------------------------------------
%  Computes AIC, SBC (BIC), FPE, HQ over a range of orders.
%  Inspect the figure that pops up — look for:
%    - Clear minimum in HQ or SBC (best for our purposes)
%    - "Elbow" in AIC/FPE if no clear minimum
%  =====================================================================
EEG = pop_est_selModelOrder(EEG, 'nogui', ...
    'modelingApproach', {'Segmentation VAR', ...
                         'algorithm',     {'Vieira-Morf'}, ...
                         'winStartIdx',   [], ...
                         'winlen',        windowLenSec, ...
                         'winstep',       windowStepSec, ...
                         'taperfcn',      'rectwin', ...
                         'epochTimeLims', epochTimeRange, ...
                         'prctWinToSample', 100, ...
                         'normalize',     [], ...
                         'detrend',       {'method', 'linear'}, ...
                         'verb',          verbosity}, ...
    'morderRange',      modelOrderRange, ...
    'downdate',         true, ...
    'runPll',           [], ...
    'icselector',       {'sbc','aic','fpe','hq'}, ...
    'winStartIdx',      [], ...
    'epochTimeLims',    epochTimeRange, ...
    'prctWinToSample',  80, ...     % subsample 80% of windows for speed
    'plot',             {'conditions',[],'icselector',{'sbc','aic','fpe','hq'}, ...
                         'minimizer',{'min'},'prclim',90}, ...
    'verb',             verbosity);

% --- PAUSE: inspect the model order figure, then set finalModelOrder ---
fprintf('\n>>> Inspect the model-order figure that just appeared.\n');
fprintf('>>> Set finalModelOrder = <value>, then run STEP 3.\n');
fprintf('>>> Reasonable starting guess: 15 for 500 Hz data.\n\n');

% Uncomment and set after inspection:
% finalModelOrder = 15;

%% =====================================================================
%  STEP 3: FIT THE FINAL VAR MODEL
%  =====================================================================
if isempty(finalModelOrder)
    error('Set finalModelOrder based on STEP 2 inspection, then rerun.');
end

EEG = pop_est_fitMVAR(EEG, 'nogui', ...
    'algorithm',     'Vieira-Morf', ...
    'morder',        finalModelOrder, ...
    'winStartIdx',   [], ...
    'winlen',        windowLenSec, ...
    'winstep',       windowStepSec, ...
    'taperfcn',      'rectwin', ...
    'epochTimeLims', epochTimeRange, ...
    'prctWinToSample', 100, ...
    'verb',          verbosity, ...
    'timer',         false);

%% =====================================================================
%  STEP 4: VALIDATE THE MODEL
%  ---------------------------------------------------------------------
%  Look at the resulting figure for:
%    - Whiteness > 0.95 (ACF) or > 0.05 (Portmanteau): residuals are white
%    - Percent consistency > 85%: model captures correlation structure
%    - Stability index < 0: model is stable/stationary
%  =====================================================================
EEG = pop_est_validateMVAR(EEG, 'nogui', ...
    'checkWhiteness',    {'alpha', 0.05, ...
                          'statcorrection', 'none', ...
                          'numAcfLags', 50, ...
                          'whitenessCriteria', {'Ljung-Box','ACF','Box-Pierce','Li-McLeod'}, ...
                          'winStartIdx', [], ...
                          'prctWinToSample', 100, ...
                          'verb', 0}, ...
    'checkConsistency',  {'winStartIdx', [], ...
                          'prctWinToSample', 100, ...
                          'Nr', [], ...
                          'donorm', 0, ...
                          'nlags', [], ...
                          'verb', 0}, ...
    'checkStability',    {'winStartIdx', [], ...
                          'prctWinToSample', 100, ...
                          'verb', 0}, ...
    'checkResidualVariance', [], ...
    'prctWinToSample',   100, ...
    'winStartIdx',       [], ...
    'verb',              verbosity, ...
    'plot',              true);

%% =====================================================================
%  STEP 5: ESTIMATE TIME-VARYING CONNECTIVITY
%  ---------------------------------------------------------------------
%  Computing several measures here — pick what you'll use in viz step.
%    dDTF08  - direct directed information flow (recommended primary)
%    nPDC    - partial directed coherence (causal source perspective)
%    nDTF    - directed transfer function (causal sink perspective)
%    S       - spectral density (power, plotted on diagonal of TF grid)
%  =====================================================================
EEG = pop_est_mvarConnectivity(EEG, 'nogui', ...
    'connmethods',  {'dDTF08','nPDC','nDTF','S'}, ...
    'absvalsq',     true, ...   % return |x|^2 for complex measures
    'spectraldecibels', true, ...
    'freqs',        freqRange, ...
    'verb',         verbosity);

%% =====================================================================
%  STEP 6: STATISTICS (optional but recommended)
%  ---------------------------------------------------------------------
%  Phase randomization gives a null distribution under H0 = no flow.
%  Use 200 permutations for exploration, 500-1000 for publication.
%  Note: this can be slow (minutes to hours).
%  =====================================================================
runStats = false;   % set true to compute
if runStats
    EEG.CAT.PConn = stat_surrogateGen(EEG, 'nogui', ...
        'modelingApproach',   EEG.CAT.configs.est_fitMVAR, ...
        'connectivityModeling', EEG.CAT.configs.est_mvarConnectivity, ...
        'mode',               {'PhaseRand','nperms',200}, ...
        'autosave',           [], ...
        'verb',               verbosity);

    EEG.CAT.Stats = stat_surrogateStats(EEG, 'nogui', ...
        'statTest',  {'Hnull'}, ...
        'tail',      'right', ...
        'computeci', false, ...
        'alpha',     0.05, ...
        'mcorrection', 'fdr', ...
        'verb',      verbosity);
end

%% =====================================================================
%  STEP 7: VISUALIZATION — Time-Frequency Grid
%  ---------------------------------------------------------------------
%  Grid of TF images: rows = "TO", columns = "FROM"
%  Diagonal shows power spectrum
%  =====================================================================
pop_vis_TimeFreqGrid(EEG, 'nogui', ...
    'MatrixLayout',  {'Partial', ...
                      'UpperTriangle','dDTF08', ...
                      'LowerTriangle','dDTF08', ...
                      'Diagonal','S'}, ...
    'clim',          99.7, ...                 % colormap saturation percentile
    'timeRange',     [], ...
    'freqValues',    freqRange, ...
    'pcontour',      [], ...
    'plotCondDiff',  false, ...
    'thresholding',  {'Simple', 'prcthresh', [97.5 3]}, ...   % visual thresholding
    'baseline',      [],...                    % e.g., [-0.5 0] if you have a true pre-event baseline
    'fighandles',    [], ...
    'smooth',        false, ...
    'xord',          [], ...
    'yord',          [], ...
    'plotorder',     [], ...
    'topoplot',      'topoplot', ...           % or 'dipole' if you have dipole locs
    'titleString',   'Time-Frequency Connectivity (dDTF08)', ...
    'titleFontSize', 12, ...
    'axesFontSize',  10, ...
    'textColor',     [1 1 1], ...
    'backgroundColor',[0 0 0]);

%% =====================================================================
%  STEP 8: VISUALIZATION — 3D Causal BrainMovie (optional, needs dipole locs)
%  =====================================================================
% Only works if you've run pop_dipfit() and have EEG.dipfit populated
if isfield(EEG,'dipfit') && ~isempty(EEG.dipfit)
    pop_vis_causalBrainMovie3D(EEG, 'nogui', ...
        'connmethod',           'dDTF08', ...
        'timeRange',            [], ...
        'freqsToCollapse',      4:8, ...        % e.g., theta band
        'collapsefun',          'integrate', ...
        'edgeColorMapping',     'Connectivity', ...
        'edgeSizeMapping',      'ConnMagnitude', ...
        'nodeColorMapping',     'Outflow', ...
        'nodeSizeMapping',      'CausalFlow', ...
        'thresholding',         {'Simple','prcthresh',95}, ...
        'rendercorticalsurface', {'on','transparency',0.7}, ...
        'projectGraphOnMRI',    'on', ...
        'OutputFormat',         {'framefolder', './brainmovie_frames'});
end

%% =====================================================================
%  Save processed dataset
%  =====================================================================
EEG = pop_saveset(EEG, 'filename', 'subject_SIFT.set', 'filepath', './');

fprintf('\nDone. Connectivity stored in EEG.CAT.Conn:\n');
disp(EEG.CAT.Conn);