function Force_data = add_length_normalized_force(Force_data, condition_indices, ignore_trials, ...
                                                  L_flexion_p1_median, L_extension_p1_median, ...
                                                  L_flexion_p3_median, L_extension_p3_median, ...
                                                  L_flexion_p6_median, L_extension_p6_median)

    for i = 1:length(Force_data)
        if ~ismember(i, ignore_trials)
            if ismember(i, condition_indices.P1)
                events_indxs = Force_data{1, i}.Events;
                for j = 1:length(Force_data{1, i}.F_cal_not_length_normalized)
                    extension_indx = events_indxs(j, 2) - events_indxs(j, 1) + 1;
                    force = Force_data{1, i}.F_cal_not_length_normalized{j};
                    Force_data{1, i}.F_cal_length_normalized = cat(1, ...
                        Force_data{1, i}.F_cal_length_normalized, ...
                        [interp1(events_indxs(j, 1):events_indxs(j, 2), force(1:extension_indx), ...
                            linspace(events_indxs(j, 1), events_indxs(j, 2), L_flexion_p1_median)), ...
                         interp1(events_indxs(j, 2)+1:events_indxs(j, 3), force(extension_indx+1:end), ...
                            linspace(events_indxs(j, 2)+1, events_indxs(j, 3), L_extension_p1_median))]);
                end
                
            elseif ismember(i, condition_indices.P3)
                events_indxs = Force_data{1, i}.Events;
                for j = 1:length(Force_data{1, i}.F_cal_not_length_normalized)
                    extension_indx = events_indxs(j, 2) - events_indxs(j, 1) + 1;
                    force = Force_data{1, i}.F_cal_not_length_normalized{j};
                    Force_data{1, i}.F_cal_length_normalized = cat(1, ...
                        Force_data{1, i}.F_cal_length_normalized, ...
                        [interp1(events_indxs(j, 1):events_indxs(j, 2), force(1:extension_indx), ...
                            linspace(events_indxs(j, 1), events_indxs(j, 2), L_flexion_p3_median)), ...
                         interp1(events_indxs(j, 2)+1:events_indxs(j, 3), force(extension_indx+1:end), ...
                            linspace(events_indxs(j, 2)+1, events_indxs(j, 3), L_extension_p3_median))]);
                end
                
            elseif ismember(i, condition_indices.P6)
                events_indxs = Force_data{1, i}.Events;
                for j = 1:length(Force_data{1, i}.F_cal_not_length_normalized)
                    extension_indx = events_indxs(j, 2) - events_indxs(j, 1) + 1;
                    force = Force_data{1, i}.F_cal_not_length_normalized{j};
                    Force_data{1, i}.F_cal_length_normalized = cat(1, ...
                        Force_data{1, i}.F_cal_length_normalized, ...
                        [interp1(events_indxs(j, 1):events_indxs(j, 2), force(1:extension_indx), ...
                            linspace(events_indxs(j, 1), events_indxs(j, 2), L_flexion_p6_median)), ...
                         interp1(events_indxs(j, 2)+1:events_indxs(j, 3), force(extension_indx+1:end), ...
                            linspace(events_indxs(j, 2)+1, events_indxs(j, 3), L_extension_p6_median))]);
                end
                
            end
        end
    end
end